// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUOTHbCSg8h8e4uIDr10cl2mFZ_ktx8E',
    appId: '1:915211159453:web:e067716fc664a3a1199174',
    messagingSenderId: '915211159453',
    projectId: 'freegapp-8f47a',
    authDomain: 'freegapp-8f47a.firebaseapp.com',
    databaseURL: 'https://freegapp-8f47a-default-rtdb.firebaseio.com',
    storageBucket: 'freegapp-8f47a.appspot.com',
    measurementId: 'G-YCJ6QFQEEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAKmJPFnVKnTGfggjDqZn__v2PTX18Ns',
    appId: '1:915211159453:android:ec93f147bd1a2a82199174',
    messagingSenderId: '915211159453',
    projectId: 'freegapp-8f47a',
    databaseURL: 'https://freegapp-8f47a-default-rtdb.firebaseio.com',
    storageBucket: 'freegapp-8f47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPgkKJxmLM3YCZhGQgFzM6wUO5Y9kYFs',
    appId: '1:915211159453:ios:56162fd8af9e145e199174',
    messagingSenderId: '915211159453',
    projectId: 'freegapp-8f47a',
    databaseURL: 'https://freegapp-8f47a-default-rtdb.firebaseio.com',
    storageBucket: 'freegapp-8f47a.appspot.com',
    iosClientId: '915211159453-8vdschnmrcu2bpounj0jpqga842asrgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.freegapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPgkKJxmLM3YCZhGQgFzM6wUO5Y9kYFs',
    appId: '1:915211159453:ios:fc397c1c96238fa2199174',
    messagingSenderId: '915211159453',
    projectId: 'freegapp-8f47a',
    databaseURL: 'https://freegapp-8f47a-default-rtdb.firebaseio.com',
    storageBucket: 'freegapp-8f47a.appspot.com',
    iosClientId: '915211159453-i9tnapihofleodija3l5sl9bind42ujv.apps.googleusercontent.com',
    iosBundleId: 'com.example.freegapp.RunnerTests',
  );
}
