# This is the name of the workflow, visible on GitHub UI
name: build CI

# Trigger the workflow on push or pull request
on: [push, pull_request]

#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

    android:
        name: flutter on Android
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - uses: subosito/flutter-action@v2
            - name: flutter version
              run: flutter --version

            - name: flutter pub get
              run: flutter pub get

            - name: flutter analyze
              run: flutter analyze

            - name: flutter test
              run: flutter test

            - name: flutter build apk
              run: flutter build apk

            - name: flutter build appbundle
              run: flutter build appbundle

    ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  architecture: x64
            - name: flutter pub get
              run: flutter pub get

            - name: flutter analyze
              run: flutter analyze

            - name: flutter test
              run: flutter test

            - name: flutter build ios
              run: flutter build ios --release --no-codesign

    linux:
        name: freegapp on Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'

            - name: sudo
              run: |
                sudo apt-get update -y
                sudo apt-get install -y ninja-build libgtk-3-dev

            - name: flutter config
              run: flutter config --enable-linux-desktop

            - name: flutter build linux
              run: flutter build linux

    # A job configuration to do some light validation of the CI configuration.
#    validate_linux:
#      runs-on: ubuntu-latest
#      name: Validate .github/workflows/flutter-build-ci.yaml
#      steps:
#          - uses: actions/checkout@v3
#          - uses: subosito/flutter-action@v2
#
#          - name: dart tool/validate_actions.dart
#            run: dart tool/validate_actions.dart
